# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pipenv rzpipe meson ninja coverage
        sudo apt-get install -y ninja-build
        
        # Install graphviz
        sudo apt-get -y install graphviz
        
        
        # Install Rizin
        sudo git clone https://github.com/rizinorg/rizin /opt/rizin/
        cd /opt/rizin/
        sudo git checkout de8a5cac5532845643a52d1231b17a7b34feb50a
        meson build
        ninja -C build
        sudo ninja -C build install
        sudo ldconfig -v
        cd -
        
        
    - name: Test with pytest
      run: |
          pipenv install --dev
          pipenv install coveralls codecov pytest-cov --skip-lock
          pipenv run pytest --cov=./

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true
          
