# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pipenv rzpipe meson ninja
        sudo apt-get install -y ninja-build
        
        # Install graphviz
        sudo apt-get -y install graphviz
        
        
        # Install Rizin
        sudo git clone --branch v0.2.1 https://github.com/rizinorg/rizin /opt/rizin/
        cd /opt/rizin/
        meson build
        ninja -C build
        sudo ninja -C build install
        sudo ldconfig -v
        cd -
        
        
    - name: Test with pytest
      run: |
          pipenv install --dev
          pipenv run pytest
