# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pipenv
        pip install meson
        sudo apt-get install -y ninja-build
        
        # Install graphviz
        sudo apt-get -y install graphviz
        
        
        # Install Rizin
        git clone https://github.com/rizinorg/rizin
        cd rizin/
        meson build
        ninja -C build
        sudo ninja -C build install
        

        
    - name: Test with pytest
      run: |
          pipenv install -e . --skip-lock --dev
          pipenv install coveralls codecov pytest-cov --skip-lock
          pipenv run pytest
