# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: setup.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest rzpipe meson==0.62.0 ninja coverage frida "frida-tools<=12.3.0" objection r2pipe==1.8.0

        # Install graphviz & ninja
        sudo apt-get -y install graphviz ninja-build
 
        # Install langchain and it's OpenAI integration
        python -m pip install langchain==0.2.11 langchain-core==0.2.23 langchain-openai==0.1.17 --upgrade

        # Install click <= 8.1.7 for CLI supports
        python -m pip install "click<=8.1.7"
        
        # Install Rust and Ares
        wget https://sh.rustup.rs -O install.sh
        sh install.sh -y
        cargo install project_ares@0.10.0

    - name: Install Shuriken-Analyzer
      run: |
        pip install git+https://github.com/Fare9/Shuriken-Analyzer.git@main#subdirectory=shuriken/bindings/Python/

    - name: Install Quark-Engine
      run: pip install .

    - name: Test with pytest
      run: |
        python -m pip install black pytest sphinx sphinx-rtd-theme
        python -m pip install coveralls pytest-cov
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}

