# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |

        python -m pip install --upgrade pip
        pip install pytest pipenv rzpipe meson ninja coverage

        # Install graphviz
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get -y install graphviz
        elif [ "$RUNNER_OS" == "Windows" ]; then
          winget install graphviz
        else
          brew install graphviz
        fi


        # Install Rizin
        sudo git clone --branch v0.2.1 https://github.com/rizinorg/rizin /opt/rizin/
        cd /opt/rizin/
        meson build
        ninja -C build
        sudo ninja -C build install

        cd -


    - name: Test with pytest
      run: |
          pipenv install --dev
          pipenv install coveralls codecov pytest-cov --skip-lock
          pipenv run pytest --cov=./

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true
          
